mutation add($x: Int!, $y: Int!) {
  add(x: $x, y: $y)
}

query hello {
  Hello
}

query dogs {
  dogs {
    name
    owner {
      name
    }
  }
}

mutation createNotification($message: String!) {
  createNotification(message: $message)
}

subscription newNotification {
  newNotification
}
